export const SHOW_CONFIRMATION_DIALOG = 'CONFIRMATION_DIALOG/SHOW';
export const HIDE_CONFIRMATION_DIALOG = 'CONFIRMATION_DIALOG/HIDE';
export const CONFIRM = 'CONFIRMATION_DIALOG/CONFIRM';
export const CANCEL = 'CONFIRMATION_DIALOG/CANCEL';
